### ISSUE TITLE
[Feat] selectArrivalView

### ISSUE THREAD

**Issue by jaehoon9186** [DeveloperAcademy-POSTECH/PickBus#28]
## 💡 Issue
루트(경로)생성 과정 중 마지막 단계인 도착정류장선택뷰를 구현합니다. 

## 📝  Todo
- [x] UI 구성
- [x] 테이블뷰, 셀 구현
- [x] 로직(정류장 선택시)
- [x] 더미 데이터로 테스트
- [x] API 데이터로 테스트
